# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen

language: julia
julia:
  - 1.3
codecov: true

jobs:
  include:
    - stage: test
      script:
        - julia -e 'using Pkg; Pkg.build(); Pkg.test("Gen", coverage=true)'
      after_success: skip
      
